package ru.publicapi.site.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiKeyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAllPropertiesEquals(ApiKey expected, ApiKey actual) {
        assertApiKeyAutoGeneratedPropertiesEquals(expected, actual);
        assertApiKeyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAllUpdatablePropertiesEquals(ApiKey expected, ApiKey actual) {
        assertApiKeyUpdatableFieldsEquals(expected, actual);
        assertApiKeyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAutoGeneratedPropertiesEquals(ApiKey expected, ApiKey actual) {
        assertThat(expected)
            .as("Verify ApiKey auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyUpdatableFieldsEquals(ApiKey expected, ApiKey actual) {
        assertThat(expected)
            .as("Verify ApiKey relevant properties")
            .satisfies(e -> assertThat(e.getKeyHash()).as("check keyHash").isEqualTo(actual.getKeyHash()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getIsActual()).as("check isActual").isEqualTo(actual.getIsActual()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyUpdatableRelationshipsEquals(ApiKey expected, ApiKey actual) {
        // empty method
    }
}
